baseurl: '/'
permalink: pretty
title: 'Jekyll Advance'
collections_dir: collections
markdown: kramdown
highlighter: rouge

sass:
  indentWidth: 4
  style: compact
  precision: 10

google_analytics_id: ''

logo:
  text_mobile: ''
  image_mobile: 'assets/images/logo/logo-mobile.svg'
  text_desktop: 'Jekyll Atlantic'
  image_desktop: 'assets/images/logo/logo.svg'
  desktop_height: '36px'

plugins:
  - jekyll-environment-variables
  - jekyll-postcss
  - jekyll-paginate

paginate: 3
paginate_path: /blog/page:num/

collections:
  posts:
    output: true
    permalink: /blog/:path/

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
  - scope:
      path: 'images'
    values:
      image: true
  - scope:
      path: 'categories'
    values:
      layout: category
      permalink: /category/:basename/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - LICENSE.md
  - LICENSE
  - README.md
